name: CI

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  pull_request:
    branches:
      - main  # or master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # Use the same version of Python as in development

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt file

      - name: Run pytest
        run: |
          pytest  # This will run your tests

      - name: Run flake8
        run: |
          flake8 .  # This will check your code for style issues
